# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2019-2021 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************

swagger: "2.0"
info:
  description: |
    The Provider VDC API allows for basic CRUD operations of a PVDC.
  title: Provider VDC API

paths:

  providerVdcs:
    get:
      x-vcloud-multisite: true
      x-vcloud-added-in: 33.0
      tags:
        - ProviderVdc
      summary: Get all provider VDCs.
      description: |
        Retrieve a list of all provider VDCs.
        Results can be filtered by context (_context).
        Supported contexts are:
        DVS (_context==dvs-NN;vimServer.id==urn:vcloud:vimserver:uuid) - |
        Returns all the provider VDCs which are related to the DVS.
        The VimServer is required for this filtering.
        External Network (_context==urn:vcloud:network:uuid) - |
        Returns all the provider VDCs which are related to the external network.
        Network Pool (_context==urn:vcloud:networkpool:uuid) - |
        Returns all the provider VDCs which are accessible to the network pool.
      operationId: getAllProviderVDCs
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryFilter"
        - $ref: "./common/query.yaml#/parameters/querySortAsc"
        - $ref: "./common/query.yaml#/parameters/querySortDesc"
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/ProviderVdcs"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"

  rootResourcePools:
    get:
      x-vcloud-added-in: 33.0
      tags:
        - ProviderVdc
      summary: Browse valid root resource pools hierarchy to back a Provider VDC.
      description: |
        Get a list of all root resource pools.
        If a resource pool is ineligible, but is in the response,
        this means it has children, which are eligible.
        A resource pool will be ineligible,
        unless the cluster has an ESXi host on it.
        The list will be sorted by name, case insensitive.
      operationId: getRootResourcePools
      parameters:
        - name: pvdcUrn
          in: path
          required: true
          type: string
          x-vcloud-constraints:
            - constraint: Urn
              args:
                - arg: providervdc
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
        - application/json
      responses:
        200:
          schema:
            $ref: "./vc/virtualCenter.yaml#/definitions/ResourcePools"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"

  childResourcePools:
    get:
      x-vcloud-added-in: 33.0
      tags:
        - ProviderVdc
      summary: Browse valid root resource pools hierarchy to back a Provider VDC.
      description: |
        Get list of child resource pools of the specified parent.
        If a resource pool is ineligible, but is in the response,
        this means it has children, which are eligible.
        A resource pool will be ineligible,
        unless the cluster has an ESXi host on it.
        The list will be sorted by name, case insensitive.
      operationId: getChildResourcePools
      parameters:
        - name: pvdcUrn
          in: path
          required: true
          type: string
          x-vcloud-constraints:
            - constraint: Urn
              args:
                - arg: providervdc
        - name: moref
          in: path
          required: true
          type: string
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
        - application/json
      responses:
        200:
          schema:
            $ref: "./vc/virtualCenter.yaml#/definitions/ResourcePools"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"

definitions:

  ProviderVdc:
    x-vcloud-added-in: 33.0
    description: |
      A provider vdc.
    type: object
    properties:
      id:
        type: string
        description: A unique identifier for the pvdc.
      name:
        type: string
        description: The name of the pvdc.
      description:
        type: string
        description:
          The description of the pvdc.
      isEnabled:
        type: boolean
        description: Whether the pvdc is enabled or not.
      maxSupportedHwVersion:
        type: string
        description: The maximum hardware version this pvdc supports.
      nsxTManager:
        x-vcloud-added-in: 33.0
        $ref: "../common/entity.yaml#/definitions/EntityReference"
        description: The NSX-T manager of the pvdc, if any.
      vimServer:
        x-vcloud-added-in: 33.0
        $ref: "../common/entity.yaml#/definitions/EntityReference"
        description: The vCenter server the pvdc belongs to.
    x-vcloud-property-annotations:
      id:
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: providervdc
          - constraint: NonSortable
      description:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      nsxTmanager:
        x-vcloud-constraints:
          - constraint: NonSortable
      vimServer:
        x-vcloud-constraints:
          - constraint: NonSortable

  ProviderVdcs:
    x-vcloud-added-in: 33.0
    description: |
      List of Provider VDCs.
    allOf:
      - $ref: "./common/query.yaml#/definitions/Page"
      - type: object
        properties:
          values:
            type: array
            items:
              $ref: "./pvdc/pvdc.yaml#/definitions/ProviderVdc"

