# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2019-2020 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************
swagger: "2.0"
info:
  description: AuditTrail types
  version: "1.0"
  title: AuditTrail YAML

paths:
  auditTrail:
    get:
      tags:
        - auditTrail
      summary: Get list of audit trail events
      description: |
        Get list of audit trail events
      operationId: queryAuditTrail
      x-vcloud-added-in: 33.0
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryFilter"
        - $ref: "./common/query.yaml#/parameters/querySortAsc"
        - $ref: "./common/query.yaml#/parameters/querySortDesc"
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/AuditTrailEvents'

  audit-trail-event-id:
    parameters:
      - name: id
        in: path
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: auditTrailEvent
    get:
      tags:
        - auditTrailUnimplemented
      summary: Retrieve an individual audit trail event.
      description: Retrieves the requested audit trail event by id.
      operationId: getAuditTrailEvent
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/AuditTrailEvent'

definitions:
  AuditTrailEvents:
    description: |
      A list of audit trail events.
    allOf:
      - $ref: '#/definitions/Page'
      - type: object
        properties:
          values:
            type: array
            description: The current page of audit trail events.
            items:
              $ref: '#/definitions/AuditTrailEvent'

  AuditTrailEvent:
    description: |
      AuditTrailEvent
    type: object
    properties:
      eventId:
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: audit
          - constraint: NonSortable
      description:
        type: string
      operatingOrg:
        $ref: "#/definitions/EntityReference"
      user:
        $ref: "#/definitions/EntityReference"
      eventEntity:
        $ref: "#/definitions/EntityReference"
      taskId:
        type: string
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      taskCellId:
        type: string
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
        x-vcloud-restricted: Visible to provider users only
      cellId:
        type: string
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
        x-vcloud-restricted: Visible to provider users only
      eventType:
        type: string
      serviceNamespace:
        type: string
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      eventStatus:
        type: string
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      timestamp:
        type: string
        format: date-time
      external:
        type: boolean
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      additionalProperties:
        type: object
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
        x-vcloud-restricted: Visible to users with the 'Perform Administrator Queries' right

  EntityReference:
    $ref: "./common/entity.yaml#/definitions/EntityReference"
  Page:
    $ref: "./common/query.yaml#/definitions/Page"