# *************************************************************************
# * Copyright 2019 VMware, Inc.  All rights reserved. VMware Confidential *
# *************************************************************************
swagger: "2.0"

info:
  title: AuditTrailEvent YAML
  description: AuditTrailEvent
  version: "1.0"


definitions:

  AuditTrailEvent:
    description: |
      AuditTrailEvent
    type: object
    properties:
      eventId:
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: audit
          - constraint: NonSortable
      description:
        type: string
      operatingOrg:
        $ref: "#/definitions/EntityReference"
      user:
        $ref: "#/definitions/EntityReference"
      eventEntity:
        $ref: "#/definitions/EntityReference"
      taskId:
        type: string
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      taskCellId:
        type: string
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
        x-vcloud-restricted: Visible to provider users only
      cellId:
        type: string
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
        x-vcloud-restricted: Visible to provider users only
      eventType:
        type: string
      serviceNamespace:
        type: string
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      eventStatus:
        type: string
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      timestamp:
        type: string
        format: date-time
      external:
        type: boolean
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      additionalProperties:
        type: object
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
        x-vcloud-restricted: Visible to users with the 'Perform Administrator Queries' right

  EntityReference:
    $ref: "./common/entity.yaml#/definitions/EntityReference"