# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2020-2021 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************

swagger: "2.0"
info:
  description: |
    The Virtual Center Storage Policy API allows for management of storage policies configured for virtual centers.
  title: Virtual Center Storage Policy API

paths:
  capabilities:
    parameters:
      - name: vcUrn
        in: path
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: vimserver
      - name: moref
        in: path
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: UUID

    get:
      x-vcloud-added-in: 34.0
      tags:
        - VirtualCenter
      summary: Retrieves capabilities of a specific Virtual Center storage policy.
      description: |
        Retrieves the current capabilities configured on a specific Virtual Center storage policy.
        These cannot be edited.
      operationId: getVcStoragePolicyCapabilities
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: './common/capability.yaml#/definitions/Capabilities'
