# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2019-2020 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************
swagger: "2.0"
info:
  description: |
    The vCloud Director Sessions API
  version: "1.0"
  title: vCloud Director Sessions API

paths:
  sessions:
    get:
      tags:
        - sessions
      summary: List all sessions for current user
      x-vcloud-added-in: 33.0
      description: |
        List all sessions for current user
      operationId: getCurrentSessions
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Sessions'

    post:
      tags:
        - sessions
      summary: Logs in a user
      x-vcloud-added-in: 33.0
      description: |
        Logs in a user
      operationId: login
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Session'
        401:
          description: Unauthorized

  session:
    parameters:
      - name: id
        in: path
        required: false
        type: string
        x-vcloud-constraints:
          - constraint: ReadOnly
          - constraint: Urn
            args:
              - arg: session
    get:
      tags:
        - sessions
      summary: Returns the specified session for current user
      x-vcloud-added-in: 33.0
      description: |
        Returns the specified session for current user
      operationId: getCurrentSession
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Session'

    delete:
      tags:
        - sessions
      summary: Logs out the current user
      x-vcloud-added-in: 33.0
      x-vcloud-multisite: true
      description: |
        Logs out the current user
      operationId: logout
      responses:
        204:
          description: No Content

  provider:
    post:
      tags:
        - sessions
      summary: Logs in a user (Provider only)
      x-vcloud-added-in: 33.0
      description: |
        Logs in a user (Provider only)
      operationId: providerLogin
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Session'
        401:
          description: Unauthorized

  accessibleLocations:
    get:
      tags:
        - sessions
      summary: Get locations accessible to this session.
      x-vcloud-added-in: 33.0
      description: |
        Gets locations accessible to this session.
      operationId: getAccessibleLocations
      produces:
        - application/json
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/AccessibleLocations'

  token:
    parameters:
      - name: id
        in: path
        required: false
        type: string
        x-vcloud-constraints:
          - constraint: ReadOnly
          - constraint: Urn
            args:
              - arg: session
    get:
      tags:
        - sessions
      summary: Get token associated with this session.
      x-vcloud-added-in: 33.0
      description: |
        Gets token associated with this session.
      operationId: getToken
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "./cpom/cpomObjects.yaml#/definitions/Token"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"

definitions:
  Sessions:
    description: |
      A list of sessions.
    allOf:
      - $ref: '#/definitions/Page'
      - type: object
        properties:
          values:
            type: array
            description: The current page of sessions.
            items:
              $ref: '#/definitions/Session'

  Session:
    description: |
      Session
    type: object
    x-vcloud-added-in: 33.0
    properties:
      id:
        type: string
        maxLength: 128
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: session
          - constraint: ReadOnly
      user:
        $ref: '#/definitions/EntityReference'
      org:
        $ref: '#/definitions/EntityReference'
      location:
        type: string
      roles:
        type: array
        items:
          type: string

  AccessibleLocations:
    description: |
      A list of locations accessible to this session.
    allOf:
      - $ref: '#/definitions/Page'
      - type: object
        properties:
          values:
            type: array
            description: The current page of accessible locations.
            items:
              $ref: './auth/accessiblelocation.yaml#/definitions/AccessibleLocation'

  EntityReferences:
    $ref: './common/entity.yaml#/definitions/EntityReferences'
  EntityReference:
    $ref: './common/entity.yaml#/definitions/EntityReference'

  Page:
    $ref: './common/query.yaml#/definitions/Page'