swagger: "2.0"
info:
  description: |
    The vCloud Director Org API.
  version: "1.0"
  title: vCloud Director Org API

paths:

  orgs:
    get:
      tags:
        - Org
      summary: Get list of all orgs accessible to the user.
      x-vcloud-added-in: 35.0
      x-vcloud-multisite: true
      x-vcloud-default-sort:
        default-sort-field: name
        sort-ascending: true
      description: |
        Get list of all orgs accessible to the user.
      operationId: queryOrgs
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryFilter"
        - $ref: "./common/query.yaml#/parameters/querySortAsc"
        - $ref: "./common/query.yaml#/parameters/querySortDesc"
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Orgs'

  org:
    parameters:
      - name: orgUrn
        in: path
        description: orgUrn
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: org
    get:
      x-vcloud-added-in: 35.0
      tags:
        - Org
      summary: Get specified organization.
      operationId: getOrg
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Org"

definitions:

  Org:
    x-vcloud-added-in: 35.0
    description: |
      An Organization.
    type: object
    properties:
      id:
        type: string
        description: A unique identifier for the organization.
      name:
        type: string
        description: Name of the organization.
        pattern: "^[a-zA-Z0-9_\\-\\.\\!\\'\\(\\),\\$]+$"
        maxLength: 128
      displayName:
        type: string
        description: Full display name of the organization.
        pattern: "(?=.*\\S.*)^[^\\p{Zl}\\p{Zp}\\p{C}]*$"
        maxLength: 128
      description:
        type: string
        default: ""
        description: Description of the organization.
        maxLength: 256
      isEnabled:
        type: boolean
        default: false
        description: Whether the organization is enabled or not.
    required:
      - name
      - displayName
  x-vcloud-property-annotations:
    id:
      x-vcloud-constraints:
        - constraint: NonSortable
        - constraint: Urn
        - constraint: ReadOnly
          args:
            - arg: org
  Orgs:
    x-vcloud-added-in: 35.0
    description: |
      A list of Organizations.
    allOf:
      - $ref: "./common/query.yaml#/definitions/Page"
      - type: object
        properties:
          values:
            type: array
            description: The current page of organizations.
            items:
              $ref: '#/definitions/Org'