# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2019-2020 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************
swagger: "2.0"
info:
  description: |
    The Cell API allows for basic CRUD operations of a Cell.
  title: Cell API

paths:

  cells:
    get:
      x-vcloud-added-in: 33.0
      tags:
        - Cell
      summary: Get cells.
      description: |
        Retrieve a list of cells
      operationId: queryCells
      x-vcloud-multisite: true
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryFilter"
        - $ref: "./common/query.yaml#/parameters/querySortAsc"
        - $ref: "./common/query.yaml#/parameters/querySortDesc"
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Cells"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"

  cell:
    get:
      x-vcloud-added-in: 33.0
      tags:
        - Cell
      summary: Get cell.
      description: |
        Retrieve a cell. Read only.
      operationId: getCell
      x-vcloud-multisite: true
      parameters:
        - name: cellUrn
          in: path
          description: cellUrn
          required: true
          type: string
          x-vcloud-constraints:
            - constraint: Urn
              args:
                - arg: cell
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Cell"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"

    delete:
      x-vcloud-added-in: 33.0
      tags:
        - Cell
      summary: Deletes a specified cell.
      operationId: deleteCell
      parameters:
        - name: cellUrn
          in: path
          description: cellUrn
          required: true
          type: string
          x-vcloud-constraints:
            - constraint: Urn
              args:
                - arg: cell
      responses:
        204:
          description: No Content

definitions:

  Cell:
    x-vcloud-added-in: 33.0
    description: |
      A vCloud Director cell.
    type: object
    properties:
      id:
        type: string
        description: The unique id of the cell.
      productBuildDate:
        type: string
        format: date-time
        description: The build date for the version of the product installed on this cell.
      isActive:
        type: boolean
        description: Cell active state.
      name:
        type: string
        description: The name of the cell.
      primaryIP:
        type: string
        description: The primary ip address of the cell.
      productVersion:
        type: string
        description: The product version of the cell.
  x-vcloud-property-annotations:
    id:
      x-vcloud-constraints:
        - constraint: NonSortable
        - constraint: Urn
        - constraint: ReadOnly
          args:
            - arg: cell
    productBuildDate:
      x-vcloud-constraints:
        - constraint: ReadOnly
        - constraint: NonSortable
        - constraint: NoNSearchable
    isActive:
      x-vcloud-constraints:
        - constraint: ReadOnly
    name:
      x-vcloud-constraints:
        - constraint: ReadOnly
    primaryIP:
      x-vcloud-constraints:
        - constraint: ReadOnly
    productVersion:
      x-vcloud-constraints:
        - constraint: ReadOnly
  Cells:
    x-vcloud-added-in: 33.0
    description: |
      A paginated list of vCloud Director cells.
    allOf:
      - $ref: "./common/query.yaml#/definitions/Page"
      - type: object
        properties:
          values:
            type: array
            items:
              $ref: "./cell/cell.yaml#/definitions/Cell"
