# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2017-2021 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************

swagger: "2.0"

info:
  title: Common networking schema objects
  description: Common networking schema objects that are used across different objects
  version: "1.0"


definitions:

  Subnets:
    description: |
      List of Subnets of a network
    type: object
    properties:
      values:
        type: array
        items:
          $ref: '#/definitions/Subnet'

  Subnet:
    description: |
      A network subnet defined by its gateway,
    type: object
    properties:
      gateway:
        type: string
        description: The gateway for the subnet.
      prefixLength:
        type: integer
        description: The netmask prefix length of the subnet.
      dnsSuffix:
        type: string
        description: The DNS suffix that VMs attached to this network will use.
      dnsServer1:
        type: string
        description: The first DNS server that VMs attached to this network will use.
      dnsServer2:
        type: string
        description: The second DNS server that VMs attached to this network will use.
      ipRanges:
        $ref: '#/definitions/IpRanges'
        description: Range of IPs within the subnet that can be used in this network. A VM attached to this network is assigned one of these IPs.
      enabled:
        type: boolean
        description: Indicates whether the external network subnet is currently enabled.

  IpRanges:
    description: |
      List of IpRange
    type: object
    properties:
      values:
        type: array
        items:
          $ref: '#/definitions/IpRange'

  IpRange:
    description: |
      An IpRange
    type: object
    properties:
      startAddress:
        type: string
        description: Starting IP address in the range.
      endAddress:
        type: string
        description: Ending IP address in the range.

  Network:
    description: |
      A network Object.
    type: object
    properties:
      id:
        type: string
        description: The unique ID for the network. This field is read-only.
      name:
        type: string
        description: The name of the network.
      description:
        type: string
        description: The description of the network.
      subnets:
        $ref: '#/definitions/Subnets'
        description: List of subnets configured for the network.
