# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2019-2020 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************
swagger: "2.0"
info:
  description: |
    API for NAT configuration of an Org VDC edge gateway. NAT rules can be setup on the Edge Gateway to map
    public facing external IP Addresses to/from private internal IP Addresses. This can only be used on an Edge Gateway backed by an NSX-T Tier-1 Gateway.
  version: "1.0"
  title: Edge Gateway NAT API

paths:

  natRules:
    parameters:
      - name: gatewayId
        in: path
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: gateway

    get:
      x-vcloud-added-in: 33.0
      tags:
        - edgeGatewayNatRules
      summary: Retrieves all NAT Rules on the edge gateway.  Pagination is supported to get the next page in the header response.
      operationId: getNatRules
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryCursor"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/EdgeNatRules'
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"

    post:
      x-vcloud-added-in: 33.0
      tags:
        - edgeGatewayNatRules
      summary: Creates a NAT Rule on the Edge Gateway.
      operationId: createNatRule
      consumes:
        - application/json
      parameters:
        - name: edgeNatRule
          in: body
          required: true
          schema:
            $ref: '#/definitions/EdgeNatRule'
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"

  natRule:
    parameters:
      - name: gatewayId
        in: path
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: gateway
      - name: ruleId
        in: path
        required: true
        type: string

    get:
      x-vcloud-added-in: 33.0
      tags:
        - edgeGatewayNatRule
      summary: Retrieves a specific NAT Rule configuration of the edge gateway based on the rule id passed in.
      operationId: getNatRule
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/EdgeNatRule'
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"

    put:
      x-vcloud-added-in: 33.0
      tags:
        - edgeGatewayNatRule
      summary: Update a specific NAT Rule configuration of the edge gateway based on the rule id passed in.
      operationId: updateNatRule
      consumes:
        - application/json
      parameters:
        - name: edgeNatRule
          in: body
          required: true
          schema:
            $ref: '#/definitions/EdgeNatRule'
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"

    delete:
      x-vcloud-added-in: 33.0
      tags:
        - edgeGatewayNatRule
      summary: Deletes a specific NAT Rule configuration of the edge gateway based on the rule id passed in.
      operationId: deleteNatRule
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"

definitions:

  EdgeNatRules:
    x-vcloud-added-in: 33.0
    description: List of configured NAT Rules.
    allOf:
    - $ref: './networking/commonObject.yaml#/definitions/NetworkingObjectStatus'
    - type: object
      properties:
        values:
          type: array
          description: The list of NAT Rules.
          items:
            $ref: './networking/edgeGatewayNat.yaml#/definitions/EdgeNatRule'

  EdgeNatRule:
    x-vcloud-added-in: 33.0
    description: The configuration for a given NAT Rule.
    type: object
    properties:
      id:
        type: string
        description: |
          The unique id of the NAT Rule. This must be supplied when updating a given NAT Rule. On creation, an unique id is generated for the NAT Rule.
      name:
        type: string
        description: User friendly name for the NAT Rule. Name must be provided.
      description:
        type: string
      enabled:
        type: boolean
        description: A flag indicating whether the individual nat rule is enabled or not. The default is true.
        default: true
      ruleType:
        $ref: '#/definitions/NatRuleType'
        description: |
            Represents the type of NAT Rule. SNAT translates an internal IP to an external ip and is used for outbound traffic.
            DNAT translates the external IP to an internal IP and is used for inbound traffic.
      applicationPortProfile:
        $ref: '#/definitions/EntityReference'
        description: |
          Represents the application ports on which the NAT Rule will be applied. An application port profile id in the form of URN format must be provided.
          If not provided then the port will be considered as "ANY".
      externalAddresses:
        type: string
        description: |
          The external addresses for the NAT Rule. This must be supplied as a single ip or Network CIDR. For a DNAT rule, this is the external facing IP Address for incoming traffic.
          For an SNAT rule, this is the external facing IP Address for outgoing traffic. These ips are typically allocated/suballocated IP Addresses on
          the Edge Gateway.
      internalAddresses:
        type: string
        description: |
          The internal addresses for the NAT Rule. This must be supplied as a single ip or Network CIDR. For a DNAT rule, this is the internal IP Address for incoming traffic.
          For an SNAT rule, this is the internal IP Address for outgoing traffic. These ips are typically the Private IPs that are allocated to workloads.
      internalPort:
         type: string
         description: |
           Port number or port range for incoming network traffic. If Any Traffic is selected for the Service, the default internal port is "ANY".
      logging:
         type: boolean
         description: A flag indicating whether logging for the individual nat rule is enabled or not. The default is false.
         default: false
      systemRule:
        type: boolean
        description: A flag indicating whether this NAT rule is managed by the system. This is not user editable
        default: false
      version:
        $ref: '#/definitions/ObjectVersion'
    required:
      - name
      - ruleType
      - internalAddresses
      - externalAddresses

    x-vcloud-property-annotations:
      id:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      name:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      description:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      enabled:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      ruleType:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      applicationPortProfile:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      externalAddresses:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      internalAddresses:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      internalPort:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      logging:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      systemRule:
        x-vcloud-constraints:
        - constraint: ReadOnly
        - constraint: NonSearchable
        - constraint: NonSortable

  NatRuleType:
    description: |
      The Nat Rule Type for a given NAT rule.
    type: object
    enum:
      - DNAT
      - SNAT

  ObjectVersion:
    $ref: './networking/commonObject.yaml#/definitions/ObjectVersion'

  EntityReference:
    $ref: "./common/entity.yaml#/definitions/EntityReference"