swagger: "2.0"
info:
  description: |
    API for L2 VPN configuration of an edge gateway. Users can create L2 VPN tunnels
    to connect two VMs on a level where each can refer to the other by their MAC
    address.
  version: "1.0"
  title: Edge Gateway L2 VPN API

paths:

  l2VpnTunnels:
    parameters:
      - name: gatewayId
        in: path
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: gateway

    get:
      x-vcloud-added-in: 35.0
      tags:
        - edgeGatewayL2VpnTunnels
      summary: Retrieves all L2 VPN tunnels for a given edge gateway.
      description: |
        Retrieves all L2 VPN tunnels that are configured for an edge gateway.
        Results can be sorted by only a single parameter. Sorting by combination of parameters (sortAsc=foo&sortDesc=bar) is not allowed.
      operationId: getL2VpnTunnels
      parameters:
        - $ref: "./common/query.yaml#/parameters/querySortAsc"
        - $ref: "./common/query.yaml#/parameters/querySortDesc"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/EdgeL2VpnTunnels'
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"
      x-vcloud-default-sort:
        default-sort-field: name
        sort-ascending: true

    post:
      x-vcloud-added-in: 35.0
      tags:
        - edgeGatewayL2VpnTunnels
      summary: Creates an L2 VPN tunnel on the Edge Gateway.
      operationId: createL2VpnTunnel
      consumes:
        - application/json
      parameters:
        - name: l2VpnTunnel
          in: body
          required: true
          schema:
            $ref: '#/definitions/EdgeL2VpnTunnel'
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"

  l2VpnTunnel:
    parameters:
      - name: gatewayId
        in: path
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: gateway
      - name: tunnelId
        in: path
        required: true
        type: string

    get:
      x-vcloud-added-in: 35.0
      tags:
        - edgeGatewayL2VpnTunnel
      summary: Retrieves a specific L2 VPN tunnel for a given edge gateway.
      operationId: getL2VpnTunnel
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/EdgeL2VpnTunnel'
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"

    put:
      x-vcloud-added-in: 35.0
      tags:
        - edgeGatewayL2VpnTunnel
      summary: Updates a specific L2 VPN tunnel for a given edge gateway.
      operationId: updateL2VpnTunnel
      consumes:
        - application/json
      parameters:
        - name: l2VpnTunnel
          in: body
          required: true
          schema:
            $ref: '#/definitions/EdgeL2VpnTunnel'
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"

    delete:
      x-vcloud-added-in: 35.0
      tags:
        - edgeGatewayL2VpnTunnel
      summary: Deletes a specific L2 VPN tunnel for a given edge gateway.
      operationId: deleteL2VpnTunnel
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"

  l2VpnTunnelStatus:
    parameters:
      - name: gatewayId
        in: path
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: gateway
      - name: tunnelId
        in: path
        required: true
        type: string
    get:
      x-vcloud-added-in: 35.0
      tags:
        - edgeGatewayL2VpnTunnel
      summary: Retrieves status of a given L2 VPN Tunnel.
      operationId: getL2VpnTunnelStatus
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/EdgeL2VpnTunnelStatus'
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"

  l2VpnTunnelStatistics:
    parameters:
      - name: gatewayId
        in: path
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: gateway
      - name: tunnelId
        in: path
        required: true
        type: string
    get:
      x-vcloud-added-in: 35.0
      tags:
        - edgeGatewayL2VpnTunnel
      summary: Retrieves connection statistics for a given L2 VPN Tunnel configured on an Edge Gateway.
      operationId: getL2VpnTunnelStatistics
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/EdgeL2VpnTunnelStatistics'
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"

definitions:

  EdgeL2VpnTunnels:
    x-vcloud-added-in: 35.0
    description: |
      List of configured L2 VPN tunnels.
    allOf:
      - $ref: './networking/commonObject.yaml#/definitions/NetworkingObjectStatus'
      - type: object
        properties:
          values:
            description: The list of L2 VPN tunnels.
            type: array
            items:
              $ref: '#/definitions/EdgeL2VpnTunnel'
            maxItems: 1000

  EdgeL2VpnTunnel:
    x-vcloud-added-in: 35.0
    description: Specifies the L2 VPN tunnel configuration.
    type: object
    properties:
      id:
        type: string
        description: |
          The unique id of this L2 VPN tunnel. On updates, the id is required for the tunnel, while for create a new id will be generated. This id is not a VCD URN.
        example: 36cc5a80-f99f-4350-b268-bb9111141a6e
      name:
        description: Name for the tunnel.
        type: string
      description:
        description: Description for the tunnel.
        type: string
      localEndpointIP:
        description: |
          The IP address of the local endpoint, which corresponds to the Edge Gateway the tunnel is being configured on.
        type: string
      remoteEndpointIP:
        description: |
          The IP address of the remote endpoint, which corresponds to the device on the remote site terminating the VPN tunnel.
        type: string
      tunnelInterface:
        description: The network CIDR block over which the session interfaces.
        type: string
      preSharedKey:
        description: This is the Pre-shared key used for authentication, no specific format is required.
        type: string
      connectorInitiationMode:
        description: |
          This is the mode used by the local endpoint to establish an IKE Connection with the remote site. The default is INITIATOR.
          <ul>
            <li>INITIATOR - Local endpoint initiates tunnel setup and will also respond to incoming tunnel setup requests from the peer gateway.</li>
            <li>RESPOND_ONLY - Local endpoint shall only respond to incoming tunnel setup requests, it shall not initiate the tunnel setup.</li>
            <li>ON_DEMAND - In this mode local endpoint will initiate tunnel creation once first packet matching the policy rule is received, and will also respond to
            incoming initiation requests.</li>
          </ul>
        type: string
        default: 'INITIATOR'
      enabled:
        description: Described whether the tunnel is enabled or not. The default is true.
        type: boolean
        default: true
      sessionMode:
        type: string
        description: |
          The current session mode, one of either SERVER or CLIENT.
          <ul>
            <li>SERVER - In which the edge gateway acts as the server side of the L2 VPN tunnel and generates peer codes to distribute to client sessions.</li>
            <li>CLIENT - In which the edge gateway receives peer codes from the server side of the L2 VPN tunnel to establish a connection.</li>
          </ul>
        default: 'SERVER'
      peerCode:
        type: string
        description: |
          This property is a base64 encoded string of the full configuration for the tunnel, generated by the server-side L2 VPN session. An L2 VPN client session must
          receive and validate this string in order to successfully establish a tunnel, but be careful sharing or storing this code since it does contain the encoded
          PSK. Leave this property blank if this call is being used to establish a server-side session.
      attachedNetworks:
        type: array
        description: |
          The list of OrgVDC Network entity references which are currently attached to this L2VPN tunnel.
          During updates, this field must contain the same networks as stretchedNetworks or be unchanged.
          During create, this field must contain the same networks as stretchedNetworks or be excluded.
        items:
          $ref: '#/definitions/EntityReference'
      stretchedNetworks:
        type: array
        description: |
          The list of OrgVDC Network entity references which are currently attached to this L2VPN tunnel.
        items:
          $ref: '#/definitions/EdgeL2VpnStretchedNetwork'
      logging:
        description: Whether logging for the tunnel is enabled or not.
        type: boolean
        default: false
      version:
        $ref: '#/definitions/ObjectVersion'

    required:
      - name
      - sessionMode
      - localEndpointIP
      - remoteEndpointIP
      - tunnelInterface
      - preSharedKey

    x-vcloud-property-annotations:
      id:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
          - constraint: ReadOnly
      name:
        x-vcloud-constraints:
            - constraint: NonSearchable
      description:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      localEndpointIP:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
          - constraint: NetworkAddress
            args:
              - arg: IPV4_IP
              - arg: IPV6_IP
      remoteEndpointIP:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
          - constraint: NetworkAddress
            args:
              - arg: IPV4_IP
              - arg: IPV6_IP
      tunnelInterface:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
          - constraint: NetworkAddress
            args:
              - arg: CIDR
      preSharedKey:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      connectorInitiationMode:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      peerCode:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      attachedNetworks:
        x-vcloud-added-in: 35.0
        x-vcloud-deprecated-in: 35.2
        x-vcloud-deprecated-alternative: stretchedNetworks
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      stretchedNetworks:
        x-vcloud-added-in: 35.2
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      enabled:
        x-vcloud-constraints:
          - constraint: NonSortable
      logging:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      version:
        x-vcloud-constraints:
          - constraint: ReadOnly

  EdgeL2VpnStretchedNetwork:
    x-vcloud-added-in: 35.2
    description: Specifies the Org vDC network that is stretched through the given L2 VPN Tunnel.
    type: object
    properties:
      networkRef:
        description: |
          The reference to the  Org vDC network entity.
        $ref: '#/definitions/EntityReference'
      tunnelId:
        description: |
          The tunnel ID assigned to the network for the L2 VPN Tunnel. Ranges from (1-4096)
        type: integer
        format: int32
    required:
      - networkRef
    x-vcloud-property-annotations:
      x-vcloud-constraints:
        networkRef:
          x-vcloud-constraints:
            - constraint: NonSearchable
            - constraint: NonSortable
        tunnelId:
          x-vcloud-constraints:
            - constraint: ReadOnly

  EdgeL2VpnTunnelStatistics:
    x-vcloud-added-in: 35.0
    description: Specifies the statistics for the given L2 VPN Tunnel.
    type: object
    properties:
      bumBytesIn:
        description: Broadcast, Unknown unicast, and Multicast (BUM) bytes in.
        type: integer
        format: int64
      bumBytesOut:
        description: Broadcast, Unknown unicast, and Multicast (BUM) bytes out.
        type: integer
        format: int64
      bumPacketsIn:
        description: Broadcast, Unknown unicast, and Multicast (BUM) packets in.
        type: integer
        format: int64
      bumPacketsOut:
        description: Broadcast, Unknown unicast, and Multicast (BUM) packets out.
        type: integer
        format: int64
      bytesIn:
        description: Total number of incoming bytes.
        type: integer
        format: int64
      bytesOut:
        description: Total number of outgoing bytes.
        type: integer
        format: int64
      packetsIn:
        description: Total number of incoming packets.
        type: integer
        format: int64
      packetsOut:
        description: Total number of outgoing packets.
        type: integer
        format: int64
      packetsReceiveError:
        description: Total number of incoming packets dropped.
        type: integer
        format: int64
      packetsSentError:
        description: Total number of packets dropped while sending for any reason.
        type: integer
        format: int64
      segmentPath:
        description: Policy path referencing the segment on which stats are gathered.
        type: string

    x-vcloud-property-annotations:
      bumBytesIn:
        x-vcloud-constraints:
          - constraint: ReadOnly
      bumBytesOut:
        x-vcloud-constraints:
          - constraint: ReadOnly
      bumPacketsIn:
        x-vcloud-constraints:
          - constraint: ReadOnly
      bumPacketsOut:
        x-vcloud-constraints:
          - constraint: ReadOnly
      bytesIn:
        x-vcloud-constraints:
          - constraint: ReadOnly
      bytesOut:
        x-vcloud-constraints:
          - constraint: ReadOnly
      packetsIn:
        x-vcloud-constraints:
          - constraint: ReadOnly
      packetsOut:
        x-vcloud-constraints:
          - constraint: ReadOnly
      packetsReceiveError:
        x-vcloud-constraints:
          - constraint: ReadOnly
      packetsSentError:
        x-vcloud-constraints:
          - constraint: ReadOnly
      segmentPath:
        x-vcloud-constraints:
          - constraint: ReadOnly

  EdgeL2VpnTunnelStatus:
    x-vcloud-added-in: 35.0
    description: |
      This includes the L2 VPN tunnel status such as whether the tunnel is up or down and the IKE Session status.
    properties:
      runtimeStatus:
        description: |
          Gives the overall L2 VPN Runtime Status (one of either UP or DOWN).
          <ul>
            <li>UP - Indicating that the tunnel connection has been successfully established.</li>
            <li>DOWN - Indicating that the tunnel connection has not yet been successfully established.</li>
          </ul>
        type: string
      failureReason:
        description: The error message which led to this tunnel's failure (if applicable).
        type: string

    x-vcloud-property-annotations:
      runtimeStatus:
        x-vcloud-constraints:
          - constraint: ReadOnly
      failureReason:
        x-vcloud-constraints:
          - constraint: ReadOnly

  ObjectVersion:
    $ref: './networking/commonObject.yaml#/definitions/ObjectVersion'

  EntityReference:
    $ref: "./common/entity.yaml#/definitions/EntityReference"