# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2018-2021 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************

swagger: "2.0"
info:
  description: |
    API for management of external networks. An external network provides the
    interface to the Internet for virtual machines connected to external
    organization vDC networks.
  version: "1.0"
  title: External Networks API

paths:

  externalNetworks:
    x-vcloud-added-in: 32.0
    get:
      tags:
      - externalNetworks
      summary: Get all external networks.
      description: |
        Get all external networks. Results can be filtered by id, name,
        backing type (networkBackings.values.backingType) and context (_context).
        Supported contexts are:
        Provider vDC ID (_context==providerVdcId) - |
        Returns all the external networks which are available to a specific Provider vDC.
        Org vDC ID (_context==orgVdcId) - |
        Returns all the external networks which are available to a specific Org vDC.
        Org vDC ID And Edge Deployment Mode (_context==orgVdcId;_context==anEdgeDeploymentMode) - |
        Returns all the external networks to which an edge gateway can connect. Edge Deployment Mode can be
        'standaloneEdgeDeployment' or 'haEdgeDeployment'. Deployment mode specifies whether to use both primary
        edge cluster and secondary edge cluster or just primary edge cluster to determine external network accessibility.
        Edge clusters are determined via vDC Network Profile for input Org vDC.
      operationId: getAllExternalNetworks
      parameters:
      - $ref: "./common/query.yaml#/parameters/queryFilter"
      - $ref: "./common/query.yaml#/parameters/querySortAsc"
      - $ref: "./common/query.yaml#/parameters/querySortDesc"
      - $ref: "./common/query.yaml#/parameters/queryPage"
      - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ExternalNetworks'
    post:
      x-vcloud-added-in: 32.0
      tags:
      - externalNetwork
      summary: Create an external network
      operationId: createExternalNetwork
      consumes:
      - application/json
      parameters:
      - name: externalNetwork
        in: body
        required: true
        schema:
          $ref: '#/definitions/ExternalNetwork'
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"

  externalNetwork:
    parameters:
    - name: externalNetworkId
      in: path
      required: true
      type: string

    get:
      x-vcloud-added-in: 32.0
      tags:
      - externalNetwork
      summary: Retrieves a specific external network.
      operationId: getExternalNetwork
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/ExternalNetwork'
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"
    delete:
      x-vcloud-added-in: 32.0
      tags:
      - externalNetwork
      summary: Deletes a specific external network.
      operationId: deleteExternalNetwork
      parameters:
      - $ref: "./common/delete.yaml#/parameters/forceDelete"
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"


definitions:

  ExternalNetworks:
    x-vcloud-added-in: 32.0
    description: |
      List of External Networks
    allOf:
    - $ref: "./common/query.yaml#/definitions/Page"
    - type: object
      properties:
        values:
          type: array
          items:
            $ref: '#/definitions/ExternalNetwork'

  ExternalNetwork:
    x-vcloud-added-in: 32.0
    description: |
      An external network.
    allOf:
    - $ref: './networking/commonObject.yaml#/definitions/Network'
    - type: object
      properties:
        networkBackings:
          $ref: './networking/externalNetworks.yaml#/definitions/ExternalNetworkBackings'
          description: |
            Backings for this external network. Describes if this external network
            is backed by port groups, vCenter standard switch or an NSX-T Tier-0 router.
        totalIpCount:
          type: integer
          description: The number of IP addresses defined by the static ip pools. If the network contains any IpV6 subnets, the total ip count will be null.
          readOnly: true
        usedIpCount:
          type: integer
          description: The number of IP address used from the static ip pools.
          readOnly: true

  ExternalNetworkBackingType:
    x-vcloud-added-in: 32.0
    description: |
      The type of the external network backing.
    type: object
    enum:
    - PORTGROUP
    - DV_PORTGROUP
    - NSXT_TIER0
    - UNKNOWN

  ExternalNetworkBackings:
    x-vcloud-added-in: 32.0
    description: |
      List of External Network backings.
    type: object
    properties:
      values:
        type: array
        items:
          $ref: '#/definitions/ExternalNetworkBacking'

  ExternalNetworkBacking:
    x-vcloud-added-in: 32.0
    description: |
      Information about an external network backing.
    type: object
    properties:
      backingId:
        type: string
        description: Unique identifier for the network backing in NSX/vCenter.
      backingType:
        $ref: '#/definitions/ExternalNetworkBackingType'
        description:
          Type of network backing.
      networkProvider:
        $ref: '../common/entity.yaml#/definitions/EntityReference'
        description: The Network Provider for the backing, either a vCenter Server or NSX-T Manager.
