# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2020-2021 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************

swagger: "2.0"
info:
  description: |
    The Load Balancer Cloud API allows for CRUD operations for Load Balancer Clouds
  title: Load Balancer Cloud API
  version: "1.0"

paths:

  loadBalancerClouds:
    post:
      x-vcloud-added-in: 35.0
      tags:
        - loadBalancerClouds
      summary: Register a new Load Balancer Cloud.
      description: |
        Register a new Load Balancer Cloud to be used with vCloud Director.
        If the Load Balancer Cloud is backed by NSXALB, DHCP on the NSXALB Cloud is required. vCloud Director will enable DHCP on the NSXALB Cloud if needed.
      operationId: registerLoadBalancerCloud
      consumes:
        - application/json
      parameters:
        - name: loadBalancerCloud
          in: body
          required: true
          schema:
            $ref: '#/definitions/LoadBalancerCloud'
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"

    get:
      x-vcloud-added-in: 35.0
      x-vcloud-multisite: true
      x-vcloud-default-sort:
        default-sort-field: name
        sort-ascending: true
      tags:
        - loadBalancerClouds
      summary: Get all registered Load Balancer Clouds in the system.
      description: |
        Retrieves all registered Load Balancer Clouds.
      operationId: getLoadBalancerClouds
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryFilter"
        - $ref: "./common/query.yaml#/parameters/querySortAsc"
        - $ref: "./common/query.yaml#/parameters/querySortDesc"
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/LoadBalancerClouds'

  loadBalancerCloud:
    parameters:
      - name: loadBalancerCloudId
        in: path
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: loadBalancerCloud

    get:
      x-vcloud-added-in: 35.0
      tags:
        - loadBalancerCloud
      summary: Get Load Balancer Cloud.
      description: |
        Retrieves a specific Load Balancer Cloud.
      operationId: getLoadBalancerCloud
      produces:
        - application/json
      responses:
        200:
          schema:
            $ref: "#/definitions/LoadBalancerCloud"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"
        404:
          $ref: "./common/response.yaml#/components/responses/NotFound"

    put:
      x-vcloud-added-in: 36.0
      tags:
        - loadBalancerCloud
      summary: Update specified Load Balancer Cloud.
      description: |
        Update an Load Balancer Cloud.
      operationId: updateLoadBalancerCloud
      consumes:
        - application/json
      parameters:
        - name: loadBalancerCloud
          in: body
          required: true
          schema:
            $ref: "#/definitions/LoadBalancerCloud"
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"

    delete:
      x-vcloud-added-in: 35.0
      tags:
        - loadBalancerCloud
      summary: Unregister the specified Load Balancer Cloud.
      description: |
        Unregister an Load Balancer Cloud.
      operationId: unregisterLoadBalancerCloud
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"

definitions:
  LoadBalancerClouds:
    x-vcloud-added-in: 35.0
    description: |
      List of Load Balancer Clouds.
    allOf:
      - $ref: "./common/query.yaml#/definitions/Page"
      - type: object
        properties:
          values:
            type: array
            items:
              $ref: '#/definitions/LoadBalancerCloud'

  LoadBalancerCloud:
    x-vcloud-added-in: 35.0
    description: |
      A Load Balancer Cloud.
    allOf:
      - $ref: './networking/commonObject.yaml#/definitions/NetworkingObjectStatus'
      - type: object
        properties:
          id:
            type: string
            description: The identifier of the registered Load Balancer Cloud in URN format
            example: urn:vcloud:loadBalancerCloud:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
          name:
            type: string
            description: |
              The name of the Load Balancer Cloud.
          description:
            type: string
            description: Description for the registered Load Balancer Cloud.
          loadBalancerCloudBacking:
            $ref: './networking/loadBalancerClouds.yaml#/definitions/LoadBalancerCloudBacking'
            description: |
              The backing that uniquely identifies
              a Load Balancer Cloud configured within a Load Balancer Controller.  At the present, VCD only
              supports NSX-T Clouds configured within an NSX-ALB Controller deployment. This is not updatable once it's created.
          networkPoolRef:
            $ref: '#/definitions/EntityReference'
            description: The Network Pool associated with this Cloud
          healthStatus:
            type: string
            description: |
              The current health status of the Load Balancer Cloud. Possible values are:
              <ul>
              <li> UP - The cloud is healthy and ready to enable Load Balancer for an Edge Gateway.
              <li> DOWN - The cloud is in a failure state. Enabling Load balancer on an Edge Gateway may not be possible.
              <li> RUNNING - The cloud is currently processing. An example is if it's enabling a Load Balancer for an Edge Gateway.
              <li> UNAVAILABLE - The cloud is unavailable.
              <li> UNKNOWN - The cloud state is unknown.
              </ul>
          detailedHealthMessage:
            type: string
            description: The non-localized detailed message on the health of the Cloud.
        required:
          - name
          - loadBalancerCloudBacking
    x-vcloud-property-annotations:
      id:
        x-vcloud-constraints:
          - constraint: NonSortable
          - constraint: ReadOnly
          - constraint: Urn
            args:
              - arg: loadBalancerCloud
      description:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      loadBalancerCloudBacking:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      networkPoolRef:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
          - constraint: ReadOnly
      healthStatus:
        x-vcloud-constraints:
          - constraint: ReadOnly
          - constraint: NonSearchable
          - constraint: NonSortable
      detailedHealthMessage:
        x-vcloud-constraints:
          - constraint: ReadOnly
          - constraint: NonSearchable
          - constraint: NonSortable
      status:
        x-vcloud-added-in: 35.0
        x-vcloud-constraints:
          - constraint: ReadOnly

  LoadBalancerCloudBacking:
    x-vcloud-added-in: 35.0
    description: |
      A Load Balancer Cloud Backing.
    type: object
    properties:
      backingId:
        type: string
        description:  The unique identifier of the Load Balancer Cloud.
        example: NSX-ALB Clouds are identified with the following format 'cloud-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
      backingType:
        type: string
        description:  The type of Load Balancer Cloud.  Valid values are NSXALB_NSXT.
        default: "NSXALB_NSXT"
      loadBalancerControllerRef:
        $ref: '#/definitions/EntityReference'
        description:  The managing Load Balancer Controller.
    required:
      - backingId
      - loadBalancerControllerRef
    x-vcloud-property-annotations:
      backingId:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      backingType:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      loadBalancerControllerRef:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable

  EntityReference:
    $ref: "./common/entity.yaml#/definitions/EntityReference"
