# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2018-2021 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************

swagger: "2.0"
info:
  description: |
    The list of NSX-T resources such as Tier-0 routers that are accessible to an organization vDC
    or all the overlay transport zones that are configured on a specific NSX-T manager.
  version: "1.0"
  title: NSX-T resources

paths:

  importableTier0Routers:
    get:
      x-vcloud-added-in: 32.0
      tags:
        - nsxTResources
      summary: Get all importable Tier-0 routers that are accessible to an organization vDC.
      description: |
        Get all Tier-0 routers that are accessible to an organization vDC. Routers that are already associated with an External Network are filtered out.
        The "_context" filter key must be set with the id of the NSX-T manager for which we want to get the Tier-0 routers for.
      operationId: getImportableTier0Routers
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryFilter"
        - $ref: "./common/query.yaml#/parameters/queryCursor"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
        - $ref: "./common/query.yaml#/parameters/querySortAsc"
        - $ref: "./common/query.yaml#/parameters/querySortDesc"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Tier0Routers'

  importableTransportZones:
    get:
      x-vcloud-added-in: 33.0
      tags:
        - nsxTResources
      summary: Get all importable overlay transport zones that are configured on an NSX-T manager.
      description: |
        Get all importable overlay transport zones that are configured on an NSX-T manager.
        Transport zones that are already associated with a network pool are filtered out.
        The "_context" filter key must be set with the id of the NSX-T manager which we want to get the transport zones for.
      operationId: getImportableTransportZones
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryFilter"
        - $ref: "./common/query.yaml#/parameters/queryCursor"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
        - $ref: "./common/query.yaml#/parameters/querySortAsc"
        - $ref: "./common/query.yaml#/parameters/querySortDesc"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/NsxTTransportZones'

definitions:

  CommonNsxTRouterFields:
    description: Common fields that all Tier-0 or Tier-1 routers have.
    properties:
      id:
        type: string
        description: The unique id of the router. Field is sortable.
      description:
        type: string
        description: The description of the router.
      displayName:
        type: string
        description: Name used in NSX-T's logs or GUI. Field is sortable.

  Tier0Routers:
    x-vcloud-added-in: 32.0
    description: |
      List of NSX-T's Tier-0 routers.
    type: object
    properties:
      values:
        type: array
        items:
          $ref: '#/definitions/Tier0Router'

  Tier0Router:
    x-vcloud-added-in: 32.0
    description: |
      An NSX-T's Tier-0 router.
    allOf:
      - $ref: './networking/nsxTResources.yaml#/definitions/CommonNsxTRouterFields'

  NsxTTransportZone:
    x-vcloud-added-in: 33.0
    description: |
      Information about a configured transport zone on an NSX-T manager.
      NSX uses transport zones to provide connectivity between hypervisors.
    properties:
      id:
        type: string
        description: The unique id of the transport zone on the NSX-T manager.
      name:
        type: string
        description: Name of Transport Zone in NSX-T Manager.
      type:
        $ref: '#/definitions/NsxTTransportZoneType'
        description: Type of a transport zone.
    x-vcloud-property-annotations:
      id:
        x-vcloud-constraints:
          - constraint: ReadOnly
          - constraint: NonSearchable
      name:
        x-vcloud-constraints:
          - constraint: NonSearchable
      type:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable

  NsxTTransportZoneType:
    x-vcloud-added-in: 33.0
    description: |
      Represents an NSX-T transport zone's traffic type.
    type: object
    enum:
      - GENEVE

  NsxTTransportZones:
    x-vcloud-added-in: 33.0
    description: |
      List of transport zones configured on an NSX-T manager.
    type: object
    properties:
      values:
        type: array
        items:
          $ref: '#/definitions/NsxTTransportZone'

  ExternalNetwork:
    $ref: "./networking/externalNetworks.yaml#/definitions/ExternalNetwork"


