# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2018-2021 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************

swagger: "2.0"
info:
  description: |
    The list of NSX-T resources such as Tier-0 or Tier-1 routers that are accessible to an organization vDC.
  version: "1.0"
  title: Organization vDC NSX-T resources

paths:

  importableTier0Routers:
    get:
      x-vcloud-added-in: 32.0
      tags:
        - nsxTResources
      summary: Get all importable Tier-0 routers that are accessible to an organization vDC.
      description: |
        Get all Tier-0 routers that are accessible to an organization vDC. Routers that are already associated with an External Network are filtered out.
        The "_context" filter key must be set with the id of the NSX-T manager for which we want to get the Tier-0 routers for.
      operationId: getImportableTier0Routers
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryFilter"
        - $ref: "./common/query.yaml#/parameters/queryCursor"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
        - $ref: "./common/query.yaml#/parameters/querySortAsc"
        - $ref: "./common/query.yaml#/parameters/querySortDesc"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Tier0Routers'

  importableTier1Routers:
    get:
      x-vcloud-added-in: 32.0
      tags:
        - nsxTResources
      summary: Get all importable Tier-1 routers that are accessible to an organization vDC.
      description: |
        Get all Tier-1 routers that are accessible to an organization vDC. Routers that are already associated with an Edge Gateway are filtered out.
        The "_context" filter key must be set with the id of the organization vDC which we want to get the Tier-1 routers for.
      operationId: getImportableTier1Routers
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryFilter"
        - $ref: "./common/query.yaml#/parameters/queryCursor"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
        - $ref: "./common/query.yaml#/parameters/querySortAsc"
        - $ref: "./common/query.yaml#/parameters/querySortDesc"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Tier1Routers'

definitions:

  CommonNsxTRouterFields:
    description: Common fields that all Tier-0 or Tier-1 routers have.
    properties:
      id:
        type: string
        description: The unique id of the router. Field is sortable.
      description:
        type: string
        description: The description of the router.
      displayName:
        type: string
        description: Name used in NSX-T's logs or GUI. Field is sortable.

  Tier0Routers:
    x-vcloud-added-in: 32.0
    description: |
      List of NSX-T's Tier-0 routers.
    type: object
    properties:
      values:
        type: array
        items:
          $ref: '#/definitions/Tier0Router'

  Tier0Router:
    x-vcloud-added-in: 32.0
    description: |
      An NSX-T's Tier-0 router.
    allOf:
      - $ref: './networking/nsxTResources.yaml#/definitions/CommonNsxTRouterFields'

  Tier1Routers:
    x-vcloud-added-in: 32.0
    description: |
      List of NSX-T's Tier-1 routers.
    type: object
    properties:
      values:
        type: array
        items:
          $ref: '#/definitions/Tier1Router'

  Tier1Router:
    x-vcloud-added-in: 32.0
    description: |
      An NSX-T's Tier-1 router.
    allOf:
      - $ref: './networking/nsxTResources.yaml#/definitions/CommonNsxTRouterFields'


