# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2019-2020 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************
swagger: "2.0"
info:
  description: |
    The vDC Network Profile API allows for management of of an Org vDC's Network Profile.
    A Given vDC Network Profile definition can contain things such as Primary/Secondary Edge Clusters, etc.
    An Org VDC, which will deploy networks/edges based on the profile.
  version: "1.0"
  title: vDC Network Profile API

paths:

  vdcNetworkProfile:
    parameters:
      - name: orgVdcId
        in: path
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: vdc

    get:
      x-vcloud-added-in: 32.0
      tags:
        - vdcNetworkProfile
      summary: Retrieves the vDC Network Profile.
      operationId: getVdcNetworkProfile
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/VdcNetworkProfile'

    put:
      x-vcloud-added-in: 32.0
      tags:
        - vdcNetworkProfile
      summary: Updates the vDC Network Profile.
      operationId: updateVdcNetworkProfile
      consumes:
        - application/json
      parameters:
        - name: vdcNetworkProfile
          in: body
          required: true
          schema:
            $ref: '#/definitions/VdcNetworkProfile'
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"

    delete:
      x-vcloud-added-in: 32.0
      tags:
        - vdcNetworkProfile
      summary: Deletes/Reset a vDC Network Profile.
      operationId: deleteVdcNetworkProfile
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"

definitions:

  VdcNetworkProfile:
    x-vcloud-added-in: 32.0
    description: |
      A vDC Network Profile object.
    type: object
    properties:
      primaryEdgeCluster:
        $ref: '#/definitions/EntityReference'
        description: The Edge Cluster where the primary appliance for an NSX-V Edge Gateway will be deployed.
      secondaryEdgeCluster:
        $ref: '#/definitions/EntityReference'
        description: The Edge Cluster where the secondary appliance for an NSX-V Edge Gateway will be deployed if HA is enabled on the Edge.
    x-vcloud-property-annotations:
      primaryEdgeCluster:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      secondaryEdgeCluster:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable

  EntityReference:
    $ref: "./common/entity.yaml#/definitions/EntityReference"