# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2019-2021 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************

swagger: "2.0"
info:
  description: |
    The vDC Network Profile API allows for management of of an Org vDC's Network Profile.
    A Given vDC Network Profile definition can contain things such as Primary/Secondary Edge Clusters, etc.
    An Org VDC, which will deploy networks/edges based on the profile.
  version: "1.0"
  title: vDC Network Profile API

paths:

  vdcNetworkProfile:
    parameters:
      - name: orgVdcId
        in: path
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: vdc

    get:
      x-vcloud-added-in: 32.0
      tags:
        - vdcNetworkProfile
      summary: Retrieves the vDC Network Profile.
      operationId: getVdcNetworkProfile
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/VdcNetworkProfile'

    put:
      x-vcloud-added-in: 32.0
      tags:
        - vdcNetworkProfile
      summary: Updates the vDC Network Profile.
      operationId: updateVdcNetworkProfile
      consumes:
        - application/json
      parameters:
        - name: vdcNetworkProfile
          in: body
          required: true
          schema:
            $ref: '#/definitions/VdcNetworkProfile'
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"

    delete:
      x-vcloud-added-in: 32.0
      tags:
        - vdcNetworkProfile
      summary: Deletes/Reset a vDC Network Profile.
      operationId: deleteVdcNetworkProfile
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"

definitions:

  VdcNetworkProfile:
    x-vcloud-added-in: 32.0
    description: |
      A vDC Network Profile object.
    type: object
    properties:
      primaryEdgeCluster:
        $ref: '#/definitions/EntityReference'
        description: The Edge Cluster where the primary appliance for an NSX-V Edge Gateway will be deployed.
      secondaryEdgeCluster:
        $ref: '#/definitions/EntityReference'
        description: The Edge Cluster where the secondary appliance for an NSX-V Edge Gateway will be deployed if HA is enabled on the Edge.
      servicesEdgeCluster:
        $ref: '#/definitions/ServicesEdgeCluster'
        description: The Edge Cluster where the DHCP server profile will be stored for NSX-T networks using NETWORK mode DHCP.
        x-vcloud-added-in: 35.0
    x-vcloud-property-annotations:
      primaryEdgeCluster:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      secondaryEdgeCluster:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      servicesEdgeCluster:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable

  ServicesEdgeCluster:
    x-vcloud-added-in: 35.0
    description: |
      This represents the Edge Cluster to be used for network services.
      This can only be used to represent Edge Clusters managed by NSX-T.
    type: object
    properties:
      edgeClusterRef:
        $ref: '#/definitions/EntityReference'
        description: The reference to VCD Edge Cluster, if it exists.
      backingId:
        type: string
        description: |
          The Id of the Edge Cluster in the NSX-T manager. If the user
          provides the id of NSX-T edge cluster during update, VCD will
          automatically create a corresponding VCD Edge cluster object
          referencing the specified NSX-T edge cluster. For NSX-V Edges,
          this is set to NULL.
    x-vcloud-property-annotations:
      edgeClusterRef:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable
      backingId:
        x-vcloud-constraints:
          - constraint: NonSearchable
          - constraint: NonSortable

  EntityReference:
    $ref: "./common/entity.yaml#/definitions/EntityReference"
