# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2017-2021 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************

swagger: "2.0"

info:
  title: Entity YAML
  description: Entity reference used to describe VCD entities
  version: "1.0"


definitions:

  EntityReferences:
    description: |
      A list of entity references.
    allOf:
      - $ref: '#/definitions/Page'
      - type: object
        properties:
          values:
            type: array
            description: The current page of entity references.
            items:
              $ref: '#/definitions/EntityReference'

  EntityReference:
    description: |
      Entity reference used to describe VCD entities
    type: object
    properties:
      name:
        type: string
      id:
        type: string

  Page:
    $ref: "./query.yaml#/definitions/Page"

