# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2017-2020 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************
swagger: "2.0"

info:
  title: Query YAML
  description: Base definitions for query endpoints
  version: "1.0"

paths:
  page-placeholder:
    get:
      tags:
        - codegenPlaceholder
      summary:  This endpoint will not produce results. It is a placeholder to enforce code generation of Page.
      description: This endpoint will not produce results. It is a placeholder to enforce code generation of Page.
      operationId: getQueryResult
      produces:
        - application/json
      responses:
        '200':
          description: The request is successful
          schema:
            $ref: '#/definitions/Page'

parameters:
  queryFilter:
    in: query
    name: filter
    required: false
    type: string
    default: ""
    description: Filter for a query.  FIQL format.
  querySortAsc:
    in: query
    name: sortAsc
    required: false
    type: string
    default: ""
    description: Field to use for ascending sort
  querySortDesc:
    in: query
    name: sortDesc
    required: false
    type: string
    default: ""
    description: Field to use for descending sort
  queryPage:
    in: query
    name: page
    required: true
    minimum: 1
    default: 1
    type: integer
    description: Page to fetch, zero offset.
  queryPageSize:
    in: query
    name: pageSize
    required: true
    minimum: 0
    maximum: 128
    default: 25
    type: integer
    description: Results per page to fetch.
  queryCursor:
    in: query
    name: cursor
    required: false
    type: string
    description: |
      Field used for getting next page of records. The value is supplied by the current result page. If not set, the first page is retrieved.
      If cursor is set, then all other pagination query parameters such as pageSize, sortDesc, sortAsc, queryFilter are ignored.

definitions:
  Page:
    description: |
      Collection of paging-related metadata to be included by composition via allOf. This type
      should be included in pageable responses to avoid duplicating these common properties. It
      is intended to be included by composition rather than inheritance. Because of this, it has
      no discriminator and should be embedded via allOf. See QueryResults for a reference usage.
    type: object
    properties:
      resultTotal:
        type: integer
        description: How many results there are in total (i.e., considering all pages).
      pageCount:
        type: integer
        description: How many pages there are in total.
      page:
        type: integer
        description: The page that was fetched, 1-indexed.
      pageSize:
        type: integer
        description: Result count for page that was fetched.
      associations:
        x-vcloud-added-in: 33.0
        type: array
        required: false
        description: Association info for each result.
        items:
          $ref: '#/definitions/Association'

  Association:
    description: |
      Site association information for an entity
    type: object
    properties:
      entityId:
        type: string
        description: ID of the entity.
      associationId:
        type: string
        description: ID of the association.
