# *************************************************************************
# * Copyright 2018 VMware, Inc.  All rights reserved. VMware Confidential *
# *************************************************************************
swagger: "2.0"

info:
  title: User YAML
  description: Common generic API responses
  version: "1.0"


components:
  responses:
    Accepted:
      description: The request have been accepted and the task to monitor the request is in the Location header.
    BadRequest:
      description: Invalid configuration.
      schema:
        $ref: "./common/error.yaml#/definitions/Error"
    NotFound:
      description: The specified resource was not found
      schema:
        $ref: "./common/error.yaml#/definitions/Error"
