swagger: "2.0"

info:
  title: Url YAML
  description: Url Spec Object
  version: "1.0"


definitions:
  Url:
    type: object
    properties:
      host:
        type: string
      port:
        type: integer
        minimum: 0
        maximum: 65535
      ssl:
        type: boolean