swagger: "2.0"
info:
  description: |
    The vCloud Director Trusted Certificates (Truststore) API
  version: "1.0"
  title: vCloud Director Trusted Certificates (Truststore) API

paths:
  trustedCertificates:
    get:
      tags:
        - trustedCertificates
      summary: Get currently trusted certificates
      x-vcloud-added-in: 34.0
      x-vcloud-multisite: true
      description: |
        Get currently trusted certificates
      operationId: queryTrustedCertificates
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryFilter"
        - $ref: "./common/query.yaml#/parameters/querySortAsc"
        - $ref: "./common/query.yaml#/parameters/querySortDesc"
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Certificates'

    post:
      tags:
        - trustedCertificates
      summary: Add to list of currently trusted certificates
      x-vcloud-added-in: 34.0
      description: |
        Add to list of currently trusted certificates
      operationId: trustCertificate
      consumes:
        - application/json
      parameters:
        - name: newCertificate
          in: body
          required: true
          schema:
            $ref: "#/definitions/TrustedCertificate"
      produces:
        - application/json
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/TrustedCertificate"

  certificate:
    parameters:
      - name: trustedCertificate
        in: path
        required: true
        type: string
        x-vcloud-constraints:
          - constraint: ReadOnly
          - constraint: Urn
            args:
              - arg: trustedCertificate
    get:
      tags:
        - trustedCertificates
      summary: Get specified certificate
      description: |
        Get the PEM-encoded certificate with the requested URN
      x-vcloud-added-in: 34.0
      operationId: getCertificate
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/TrustedCertificate"

    put:
      tags:
        - trustedCertificates
      summary: Updates an existing trusted certificate
      x-vcloud-added-in: 34.0
      description: |
        Updates an existing trusted certificate
      operationId: updateCertificate
      consumes:
        - application/json
      parameters:
        - name: modifiedCertificate
          in: body
          required: true
          schema:
            $ref: "#/definitions/TrustedCertificate"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/TrustedCertificate"

    delete:
      tags:
        - trustedCertificates
      summary: Revoke trusting specified certificate
      description: |
        Revoke trusting specified certificate
      x-vcloud-added-in: 34.0
      operationId: deleteCertificate
      responses:
        204:
          description: No Content

definitions:
  Certificates:
    description: |
      A list of certificates.
    x-vcloud-added-in: 34.0
    allOf:
      - $ref: './common/query.yaml#/definitions/Page'
      - type: object
        properties:
          values:
            type: array
            description: The current page of certificates.
            items:
              $ref: '#/definitions/TrustedCertificate'

  TrustedCertificate:
    description: |
      SSL certificate in PEM format.
    type: object
    x-vcloud-added-in: 34.0
    properties:
      id:
        type: string
        maxLength: 128
        x-vcloud-constraints:
          - constraint: Urn
            args:
              - arg: trustedCertificate
          - constraint: ReadOnly
      alias:
        type: string
        maxLength: 255
      certificate:
        type: string
        description: PEM encoded certificate
        x-vcloud-constraints:
          - constraint: NonSortable
          - constraint: Certificate
        example: -----BEGIN CERTIFICATE-----
                 <sample certificate contents>
                 -----END CERTIFICATE-----
    required:
      - alias
      - certificate
