# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2020-2021 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************

swagger: "2.0"
info:
  description: |
    The Cloud Director Allowed Origins API
  version: "1.0"
  title: Cloud Director Allowed Origins API

paths:
  cors:
    get:
      tags:
        - cors
      summary: Queries CORS allowed origins.
      x-vcloud-added-in: 36.0
      x-vcloud-multisite: true
      x-vcloud-default-sort:
        default-sort-field: origin
        sort-ascending: true
      description: |
       Queries the set of allowed origins.
      operationId: queryAllowedOrigins
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryFilter"
        - $ref: "./common/query.yaml#/parameters/querySortAsc"
        - $ref: "./common/query.yaml#/parameters/querySortDesc"
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/AllowedOrigins'
    put:
      tags:
        - cors
      summary: Sets allowed origins to the given set of origins.
      x-vcloud-added-in: 36.0
      x-vcloud-event: com/vmware/vcloud/event/cors/allowedOrigins/modify
      operationId: setAllowedOrigins
      consumes:
        - application/json
      parameters:
        - name: allowedOrigins
          in: body
          required: true
          schema:
            $ref: "#/definitions/AllowedOrigins"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/AllowedOrigins"

definitions:
  AllowedOrigins:
    x-vcloud-added-in: 36.0
    description: |
      A list of Allowed Origins.
    allOf:
      - $ref: "./common/query.yaml#/definitions/Page"
      - type: object
        properties:
          values:
            type: array
            description: The current page of allowed origins.
            items:
              $ref: './site/site-settings-cors.yaml#/definitions/AllowedOrigin'

  AllowedOrigin:
    x-vcloud-added-in: 36.0
    description: |
      An origin for which CORS is allowed.
    type: object
    properties:
      origin:
        type: string
        description: The origin that will be allowed.
