# ******************************************************************************
# * api-extension-template-vcloud-director
# * Copyright 2020-2021 VMware, Inc.  All rights reserved. *
# * SPDX-License-Identifier: BSD-2-Clause
# ******************************************************************************

swagger: "2.0"

info:
  title: Definitions of Defined Entity Behaviors
  description: Defined Entity Behaviors can be executed on selected Defined Entities
  version: "1.0"

definitions:
  Behaviors:
    x-vcloud-added-in: 35.0
    description: |
      An array ofs Defined Entity Behaviors
    allOf:
      - $ref: "./common/query.yaml#/definitions/Page"
      - type: object
        properties:
          values:
            type: array
            items:
              $ref: '#/definitions/Behavior'

  Behavior:
    x-vcloud-added-in: 35.0
    description: |
      The descriptor of a Defined Entity Behavior
    type: object
    properties:
      name:
        type: string
        example: addNode
      id:
        description: The Behavior ID is generated and is an output-only property
        type: string
        example: urn:vcloud:behavior-type:addNode:vendorA:pksContainerCluster:1.0.0:vendorA:containerCluster:1.0.0
        x-vcloud-constraints:
          - constraint: NonSortable
          - constraint: ReadOnly
          - constraint: NonSearchable
      ref:
        description: The Behavior invocation reference to be used for polymorphic behavior invocations. It is generated and is an output-only property
        type: string
        example: urn:vcloud:behavior-interface:testNode:vendorA:containerCluster:1.0.0
        x-vcloud-constraints:
          - constraint: NonSortable
          - constraint: ReadOnly
          - constraint: NonSearchable
      description:
        description: A description specifying the contract of the Behavior
        type: string
        example: |
          Adds a node to the cluster.
          Parameters:
            clusterId: the ID of the cluster
            node: The node address
        x-vcloud-constraints:
          - constraint: NonSortable
          - constraint: ReadOnly
          - constraint: NonSearchable
      execution:
        description: The Behavior execution mechanism. Can be defined both in an Interface and in a Defined Entity Type as an override.
        type: object
        additionalProperties:
          type: object
        x-vcloud-constraints:
          - constraint: NonSortable
          - constraint: ReadOnly
          - constraint: NonSearchable

  BehaviorInvocation:
    x-vcloud-added-in: 35.0
    description: |
      An invocation of a Behavior on a Defined Entity instance.
      Currently the Behavior interfaces are key-value maps specified in the Behavior description.
    type: object
    properties:
      arguments:
        description: The arguments to be passed to the invoked Behavior
        type: object
        additionalProperties: true
        example: |
          { "node": "server-242.company.com", ... }
      metadata:
        description: Metadata to be passed to the invoked Behavior
        type: object
        additionalProperties: true
        example: |
          { "operationId": "event35262", ... }

  BehaviorAccess:
    x-vcloud-added-in: 35.0
    description: |
      A definition of an access control configuration of a Behavior.
    type: object
    properties:
      behaviorId:
        description: The ID of the Behavior. It can be both a behavior-interface or an overriden behavior-type ID.
        type: string
        example: urn:vcloud:behavior-interface:testNode:vendorA:containerCluster:1.0.0
        x-vcloud-constraints:
          - constraint: NonSortable
          - constraint: ReadOnly
          - constraint: NonSearchable
      accessLevelId:
        description: The ID of an AccessLevel.
        type: string
        example: urn:vcloud:accessLevel:ReadOnly
        x-vcloud-constraints:
          - constraint: NonSortable
          - constraint: ReadOnly
          - constraint: NonSearchable

  BehaviorAccesses:
    x-vcloud-added-in: 35.0
    description: |
      The access control configuration of all Defined Enitty Type's Behaviors.
    allOf:
      - $ref: '#/definitions/Page'
      - type: object
        properties:
          values:
            type: array
            description: The current page of behavior access entries
            items:
              $ref: '#/definitions/BehaviorAccess'


