swagger: "2.0"

info:
  title: Defined Entity Types
  description: Types for defined entities are used for classification and json schema definition.
  version: "1.0"

paths:
  defined-entity-types:
    get:
      tags:
        - definedEntityType
      x-vcloud-added-in: 35.0
      x-vcloud-multisite: true
      summary: Gets the collection of entity types defined in the vCD instance. Allows collection refinement through traditional FIQL-based filtering
      description: Gets the collection of entity types defined in the vCD instance. Allows collection refinement through traditional FIQL-based filtering
      operationId: getDefinedEntityTypes
      produces:
        - application/json
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryFilter"
        - $ref: "./common/query.yaml#/parameters/querySortAsc"
        - $ref: "./common/query.yaml#/parameters/querySortDesc"
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      responses:
        200:
          description: Ok
          schema:
            $ref: "#/definitions/DefinedEntityTypes"
    post:
      tags:
        - definedEntityType
      x-vcloud-added-in: 35.0
      summary: Creates a defined entity type.
      description: Creates a defined entity type.
      operationId: createDefinedEntityType
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: definition
          in: body
          required: true
          schema:
            $ref: "#/definitions/DefinedEntityType"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/DefinedEntityType"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"

  defined-entity-type:
    parameters:
      - name: id
        in: path
        required: true
        type: string
        example: urn:vcloud:type:vmware:vspheresddc:1.0.0
    get:
      x-vcloud-added-in: 35.0
      tags:
        - definedEntityType
      summary: Gets the entity type with the unique identifier (URN)
      description: Gets the entity type with the unique identifier (URN)
      operationId: getDefinedEntityType
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/DefinedEntityType"
    delete:
      tags:
        - definedEntityType
      x-vcloud-added-in: 35.0
      summary: Deletes the entity type with the unique identifier (URN)
      description: Deletes the entity type with the unique identifier (URN)
      operationId: deleteDefinedEntityType
      responses:
        204:
          description: No Content
    put:
      tags:
        - definedEntityType
      x-vcloud-added-in: 35.0
      summary: Updates the entity type with the unique identifier (URN)
      description: Updates the entity type with the unique identifier (URN)
      operationId: updateDefinedEntityType
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: definition
          in: body
          required: true
          schema:
            $ref: "#/definitions/DefinedEntityType"
      responses:
        200:
          description: Ok
          schema:
            $ref: "#/definitions/DefinedEntityType"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"
    post:
      tags:
        - definedEntity
      x-vcloud-added-in: 35.0
      summary: Creates a defined entity based on the entity type (URN).
      description: Creates a defined entity based on the entity type (URN).
      operationId: createDefinedEntity
      consumes:
        - application/json
      parameters:
        - name: entity
          in: body
          required: true
          schema:
            $ref: "./extensibility/definedEntity.yaml#/definitions/DefinedEntity"
      responses:
        202:
          $ref: "./common/response.yaml#/components/responses/Accepted"
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"

  behaviors:
    parameters:
      - name: id
        in: path
        required: true
        type: string
    get:
      tags:
        - definedInterfaceBehaviors
      summary: Get the Behaviors of the Defined Entity Type.
      x-vcloud-added-in: 35.0
      description: |
        Retrieve the Behaviors of the specified Defined Entity Type.
      operationId: getDefinedEntityTypeBehaviors
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: './extensibility/behavior.yaml#/definitions/Behaviors'

  behavior:
    parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: behaviorId
        in: path
        required: true
        type: string
    get:
      tags:
        - definedInterfaceBehaviors
      summary: Get a Behavior in the Defined Type
      x-vcloud-added-in: 35.0
      description: |
        Retrieve a specific Behavior in the Defined Type.
        The Behavior must be specified by ID.
      operationId: getTypeBehavior
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: './extensibility/behavior.yaml#/definitions/Behavior'
    put:
      tags:
        - definedInterfaceBehaviors
      summary: Update the execution of the specified Behavior in the Defined Entity Type
      x-vcloud-added-in: 35.0
      description: |
        Override the execution of the specified Behavior in the Defined Entity Type.
        The Behavior must be specified by ID.
      operationId: updateTypeBehavior
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: behavior
          in: body
          required: true
          schema:
            $ref: './extensibility/behavior.yaml#/definitions/Behavior'
      responses:
        200:
          description: OK
          schema:
            $ref: './extensibility/behavior.yaml#/definitions/Behavior'
    delete:
      tags:
        - definedInterfaceBehaviors
      summary: Remove a Behavior override from the Defined Entity Type.
      x-vcloud-added-in: 35.0
      description: |
        Remove a Behavior override in the Defined Entity Type.
        The Behavior must be specified by ID.
      operationId: removeBehaviorOverride
      responses:
        204:
          description: No Content

  defined-entity-type-access:
    parameters:
      - name: id
        in: path
        required: true
        type: string
        example: urn:vcloud:type:vmware:vspheresddc:1.0.0
    get:
      x-vcloud-added-in: 35.0
      tags:
        - definedInterfaceBehaviors
      summary: Gets the access control configuration of the entity type's behaviors
      description: Gets the access control configuration of the entity type's behaviors
      operationId: getDefinedEntityTypeAccess
      parameters:
        - $ref: "./common/query.yaml#/parameters/queryPage"
        - $ref: "./common/query.yaml#/parameters/queryPageSize"
      produces:
        - application/json
      x-vcloud-default-sort:
        default-sort-field: behaviorId
        sort-ascending: true
      responses:
        200:
          description: OK
          schema:
            $ref: './extensibility/behavior.yaml#/definitions/BehaviorAccesses'
    put:
      tags:
        - definedInterfaceBehaviors
      x-vcloud-added-in: 35.0
      summary: Sets the access control configuration of the entity type's behaviors
      description: Sets the access control configuration of the entity type's behaviors
      operationId: setDefinedEntityTypeAccess
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: definition
          in: body
          required: true
          schema:
            $ref: './extensibility/behavior.yaml#/definitions/BehaviorAccesses'
      responses:
        200:
          description: Ok
          schema:
            $ref: './extensibility/behavior.yaml#/definitions/BehaviorAccesses'
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"
    post:
      tags:
        - definedInterfaceBehaviors
      x-vcloud-added-in: 35.0
      summary: Adds an access control configuration of an entity type's behavior
      description: Adds an access control configuration of an entity type's behavior
      operationId: addDefinedEntityTypeAccess
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: definition
          in: body
          required: true
          schema:
            $ref: './extensibility/behavior.yaml#/definitions/BehaviorAccess'
      responses:
        200:
          description: Ok
          schema:
            $ref: './extensibility/behavior.yaml#/definitions/BehaviorAccess'
        400:
          $ref: "./common/response.yaml#/components/responses/BadRequest"


definitions:
  DefinedEntityType:
    x-vcloud-added-in: 35.0
    description: |
      Describes what a defined entity type should look like.
    type: object
    properties:
      id:
        type: string
        example: urn:vcloud:type:vmware:vspheresddc:1.0.0
        description: |
          The id of the defined entity type in URN format.
        x-vcloud-constraints:
          - constraint: NonSortable
          - constraint: ReadOnly
      name:
        type: string
        example: vspheresddc
        description: |
          The name of the defined entity type.
      description:
        type: string
        description: |
          Description of the defined entity type.
      nss:
        type: string
        example: sddc
        description: |
          A unique namespace specific string. The combination of nss and version
          must be unique.
      version:
        type: string
        x-vcloud-constraints:
          - constraint: Version
        example: 1.0.0
        description: |
          The version of the defined entity type. The combination of nss and version
          must be unique. The version string must follow semantic versioning rules.
      externalId:
        type: string
        example: 123
        description: |
          An external entity's id that this definition may apply to.
      schema:
        type: object
        example:
          application/json: {"type": "object", "properties": {"rectangle": {"$ref": "#/definitions/Rectangle"}}, "definitions": {"size": {"type": "number", "minimum": 0}, "Rectangle": {"type": "object", "properties": {"a": {"$ref": "#/definitions/size"}, "b": {"$ref": "#/definitions/size"}}}}}
        description: |
          The JSON-Schema valid definition of the defined entity type.
          If no JSON Schema version is specified, version 4 will be assumed.
        additionalProperties:
          type: object
          example:
            - prop1: value1
            - prop2: value2
      vendor:
        type: string
        description: |
          The vendor name.
        example: vmware
      interfaces:
        type: array
        items:
          type: string
        minItems: 0
        example:
          - urn:vcloud:interface:vmware.sddc:1.0.0
        description: |
          List of interface ids that this defined entity type is referenced by.
      readonly:
        type: boolean
        x-vcloud-constraints:
          - constraint: ReadOnly
        example: false
        description: True if the entity type cannot be modified.
      required:
        - vendor
        - version
        - name
        - nss
        - schema

  DefinedEntityTypes:
    x-vcloud-added-in: 35.0
    description: |
      A list of defined entity types.
    allOf:
      - $ref: '#/definitions/Page'
      - type: object
        properties:
          values:
            type: array
            description: The current page of defined entity types.
            items:
              $ref: '#/definitions/DefinedEntityType'
